# Generated by Django 5.0.2 on 2024-02-26 16:23

import db.models.workspace
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(20, 'Owner'), (15, 'Admin'), (10, 'Member'), (5, 'Guest')], default=10)),
                ('company_role', models.TextField(blank=True, null=True)),
                ('view_props', models.JSONField(default=db.models.workspace.get_default_props)),
                ('default_props', models.JSONField(default=db.models.workspace.get_default_props)),
                ('issue_props', models.JSONField(default=db.models.workspace.get_issue_props)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_workspace', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Member',
                'verbose_name_plural': 'Workspace Members',
                'db_table': 'workspace_members',
                'unique_together': {('workspace', 'member')},
            },
        ),
    ]
