# Generated by Django 5.0.2 on 2024-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
