# Generated by Django 5.0.2 on 2024-02-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_verificationcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='request_count',
        ),
    ]
